# Copyright 2011 Obsidian Research Corp. GPLv2, see COPYING.
# -*- coding: utf-8 -*-


__all__ = [
    "libib_name_map_perfquery",
    "libib_name_map_saquery",
    "libib_name_map_smpquery",
]


# libib has all sorts of interesting ideas what to name the fields. We don't, ours
# are uniform. These tables switch our names to libib's. This isn't perfect, libib
# is somewhat context sensitive to how it chooses a name. :(
libib_name_map_saquery = {
    # saquery
    "nodeDescription": "NodeDescription",
    "RespTimeValue": "Response time value",
    "SGID": "sgid",
    "ClassVersion": "Class version",
    "CapabilityMask2": "Capability mask 2",
    "DGID": "dgid",
    "SLID": "slid",
    "CapabilityMask": "Capability mask",
    "ServiceID": "service_id",
    "DLID": "dlid",
    "SL": "sl",
    "PKey": "pkey",
    "TClass": "tclass",
    "BaseVersion": "Base version",
    "PortGID": "PortGid",
    "BlockNum": "Block",
    "InputPortNum": "InPort",
    "OutputPortNum": "OutPort",
    "RedirectGID": "Redirect GID",
    "RedirectLID": "Redirect LID",
    "RedirectQP": "Redirect QP",
    "RedirectQKey": "Redirect QKey",
    "RedirectPKey": "Redirect PKey",
    "MLID": "mlid",
    "MTU": "mtu",
    "PacketLifeTime": "pkt_life",
    "Preference": "preference",
    "Rate": "rate",
    "QKey": "qkey",
    "QOSClass": "qos_class",
    "OutPort": "Port",
    "EndportLID": "EndPortLid",
    "TrapPKey": "Trap PKey",
    "TrapQKey": "Trap QKey",
    "TrapGID": "Trap GID",
    "TrapLID": "Trap LID",
    "PortNum": "Port",

    # Structure names.
    "SAServiceRecord": "ServiceRecord",
    "SALinkRecord": "LinkRecord",
    "SASMInfoRecord": "SMInfoRecord",
    "SANodeRecord": "NodeRecord",
    "SAPortInfoRecord": "PortInfoRecord",
    "SASwitchInfoRecord": "SwitchInfoRecord",
    "SAPathRecord": "PathRecord",
    "MADClassPortInfo": "SA ClassPortInfo",
    "SAMCMemberRecord": "MCMember Record",
    "SAServiceAssociationRecord": "ServiceAssociationRecord",
    "SAGUIDInfoRecord": "GUIDInfoRecord",
    "SAVLArbitrationTableRecord": "VLArbTableRecord",
    "SASLToVLMappingTableRecord": "SL2VLTableRecord",
    "SAPKeyTableRecord": "PKeyTableRecord",
    "SARandomForwardingTableRecord": "RandomForwardingTableRecord",
    "SALinearForwardingTableRecord": "LFT Record",
    "SAMulticastForwardingTableRecord": "MFT Record",
    "SAInformInfoRecord": "InformInfoRecord",

    "NodeType": "node_type",
    "NumPorts": "num_ports",
    "SystemImageGUID": "sys_guid",
    "NodeGUID": "node_guid",
    "PortGUID": "port_guid",
    "PartitionCap": "partition_cap",
    "LocalPortNum": "port_num",
    "VendorID": "vendor_id",
    "DeviceID": "device_id",
    "revision": "revision",
}

# FIXME: I think Ira fixed libib to be more sane, so these are old.
libib_name_map_perfquery = {
    "PortRcvErrors": "RcvErrors",
    "PortXmitConstraintErrors": "XmtConstraintErrors",
    "SymbolErrorCounter": "SymbolErrors",
    "PortXmitDiscards": "XmtDiscards",
    "PortRcvRemotePhysicalErrors": "RcvRemotePhysErrors",
    "ExcessiveBufferOverrunErrors": "ExcBufOverrunErrors",
    "PortXmitData": "XmtData",
    "LinkErrorRecoveryCounter": "LinkRecovers",
    "PortRcvSwitchRelayErrors": "RcvSwRelayErrors",
    "PortXmitWait": "XmtWait",
    "LocalLinkIntegrityErrors": "LinkIntegrityErrors",
    "PortRcvData": "RcvData",
    "PortRcvConstraintErrors": "RcvConstraintErrors",
    "LinkDownedCounter": "LinkDowned",
    "PortXmitPkts": "XmtPkts",
    "PortSwHOQLimitDiscards": "PortSwHOQLifetimeLimitDiscards",
    "PortRcvPkts": "RcvPkts",
}

libib_name_map_smpquery = {
    "PartitionEnforcementCap": "PartEnforceCap",
    "VendorID": "VendorId",
    "LinkDownDefaultState": "LinkDownDefState",
    "InitTypeReply": "InitReply",
    "MTUCap": "MtuCap",
    "PortPhysicalState": "PhysLinkState",
    "DefaultPort": "DefPort",
    "PKeyViolations": "PkeyViolations",
    "RespTimeValue": "RespTimeVal",
    "OverrunErrors": "OverrunErr",
    "LinkRoundTripLatency": "RoundTrip",
    "SubnetTimeOut": "SubnetTimeout",
    "MasterSMSL": "SMSL",
    "MKeyViolations": "MkeyViolations",
    "MulticastFDBCap": "McastFdbCap",
    "VLArbitrationHighCap": "VLArbHighCap",
    "MKeyProtectBits": "ProtectBits",
    "LifeTimeValue": "LifeTime",
    "ClassVersion": "ClassVers",
    "DefaultMulticastPrimaryPort": "DefMcastPrimPort",
    "LinearFDBTop": "LinearFdbTop",
    "PortState": "LinkState",
    "BaseVersion": "BaseVers",
    "DefaultMulticastNotPrimaryPort": "DefMcastNotPrimPort",
    "QKeyViolations": "QkeyViolations",
    "FilterRawOutbound": "FilterRawOutb",
    "OperationalVLs": "OperVLs",
    "LocalPortNum": "LocalPort",
    "FilterRawInbound": "FilterRawInb",
    "CapabilityMask": "CapMask",
    "HOQLife": "HoqLife",
    "GUIDCap": "GuidCap",
    "MKeyLeasePeriod": "MkeyLeasePeriod",
    "PartitionEnforcementOutbound": "PartEnforceOutb",
    "LocalPhyErrors": "LocalPhysErr",
    "NodeGUID": "Guid",
    "DeviceID": "DevId",
    "LID": "Lid",
    "LinearFDBCap": "LinearFdbCap",
    "SystemImageGUID": "SystemGuid",
    "MKey": "Mkey",
    "VLArbitrationLowCap": "VLArbLowCap",
    "PortGUID": "PortGuid",
    "RandomFDBCap": "RandomFdbCap",
    "PortStateChange": "StateChange",
    "PartitionEnforcementInbound": "PartEnforceInb",
    "GIDPrefix": "GidPrefix",
    "FilterRawInboundCap": "FilterRawInbound",
    "FilterRawOutboundCap": "FilterRawOutbound",
    "OutboundEnforcementCap": "OutboundPartEnf",
    "InboundEnforcementCap": "InboundPartEnf",
    "PartitionCap": "PartCap",
    "MasterSMLID": "SMLid",
    "OptimizedSLtoVLMappingProgramming": "OptSLtoVLMapping",
    "LIDsPerPort": "LidsPerPort",
}
